### ISSUE TITLE
Button style broken on v0.10.5

### ISSUE THREAD

**Issue by jhen0409** [ptmt/react-native-macos#124]
![2016-11-06 11 33 42](https://cloud.githubusercontent.com/assets/3001525/20039115/a16d2f7a-a479-11e6-8105-e8207e347425.png)

With init project:

```js
<View style={styles.container}>
  <Button title="Test Button" />
</View>
```

I'm using macOS 10.12.2 Beta (16C32f) and Xcode 8.1 (8B62) with template of `react-native-macos-cli@0.2.1`.

**Comment by ptmt** [comment]
Thanks for the issue, Sierra has new convenient constructors, I have the fix locally, but need to support the previous version. Will prepare and fix it soon.

**Comment by ptmt** [comment]
Can you try 0.11.0-rc from npm? I've also added new example of simpliest button example: 

![image](https://cloud.githubusercontent.com/assets/1004115/20056976/ebd4a892-a4f9-11e6-8158-39584128ffec.png)

This new constructor is useful for touchbar.

**Comment by jhen0409** [comment]
Thank you @ptmt, it work! :)

**Comment by knoopx** [comment]
I'm getting this when using `0.11.0-rc` running on OSX 10.11.6 (15G1108)

```
node_modules/react-native-macos/React/Views/RCTButtonManager.m:58:38: error: use of undeclared identifier 'NSAppKitVersionNumber10_12'; did you mean 'NSAppKitVersionNumber'?
  if (floor(NSAppKitVersionNumber) < NSAppKitVersionNumber10_12)
                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~
                                     NSAppKitVersionNumber
```

**Comment by ptmt** [comment]
Thanks, it seems preprocessor macro should be there, I'll fix that in next release candidate.

**Comment by ptmt** [comment]
Should work on 10.11 now, could you try please when you have time.

**Comment by knoopx** [comment]
@ptmt 40d2b39 /  `0.11.0-rc1` build succeeds but `<TextInput>` and `<Button>` seems to be broken now, at least on OSX 10.11:

![image](https://cloud.githubusercontent.com/assets/100993/20245310/b7e00654-a99e-11e6-9965-910622bdd8d5.png)

![image](https://cloud.githubusercontent.com/assets/100993/20245265/b9fcc3a6-a99d-11e6-8441-ccc1bf006fa5.png)

**Comment by knoopx** [comment]
It looks like the component views don't properly adjust to fit their content height. If I override the height they properly render again.

**Comment by ptmt** [comment]
@knoopx Supposedly fixed Button's default height for 10.11 in https://github.com/ptmt/react-native-macos/commit/a296de4c81951fcc2d02a51e1eede5fdf3d40d92.
